language: node_js
node_js:
- 10.19.0
notifications:
  email: false
cache:
  directories:
  - node_modules
script:
- npm run prod
addons:
  ssh_known_hosts: 188.225.18.51
env:
  REACT_APP_API_HTTP: 188.225.18.51:3000
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: develop
