language: node_js
node_js:
- 10.19.0
notifications:
  email: false
cache:
  directories:
  - node_modules
script:
- npm run prod
addons:
  ssh_known_hosts: 188.225.18.51
env:
  REACT_APP_API_HTTP: 188.225.18.51:3000
before_deploy:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
    -in id_rsa.enc -out id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ web@188.225.18.51:/home/web/projects/shop
  on:
    branch: develop
