language: node_js
node_js:
  - 12.16.1
cache:
  directories:
    - node_modules
script:
  - npm ci
addons:
  ssh_known_hosts: 188.225.18.51
before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
    -in id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ web@188.225.18.51:/home/web/projects/shop
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: ssh web@188.225.18.51 "pm2 pm2 deploy ecosystem.config.js staging setup && pm2 deploy ecosystem.config.js staging && pm2 save"
    on:
      branch: develop
